[package]
name = "minterest-cli"
version = "0.5.0"
authors = ["Minterest <https://github.com/minterest-defi>"]
edition = "2018"

[dependencies]
structopt = "0.3.8"
sp-core = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", optional = true }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", optional = true }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", optional = true }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", optional = true }
service = { package = "minterest-service", path = "../service", default-features = false, optional = true }
node-minterest-runtime = { path = '../runtime' }

[build-dependencies]
substrate-build-script-utils = { version = "3.0.0", default-features = false }
#substrate-build-script-utils = { git = "https://github.com/paritytech//substrate", rev = "2be8fcc4236d32786c62f6f27a98e7fe7e550807" }

[features]
default = ["wasmtime", "cli"]
wasmtime = [ "sc-cli/wasmtime" ]
cli = [
    "service",
    "sp-core",
    "sc-cli",
    "sc-service",
    "frame-benchmarking-cli",
]
runtime-benchmarks = [ "service/runtime-benchmarks" ]
